In [1]:
import numpy as np

In [2]:
x=[1,4,5,7]

In [3]:
y=[8,7,9]

In [4]:
np.save('testx',x)

In [5]:
loadx=np.load('testx.npy')

In [19]:
loadx

array([1, 4, 5, 7])

In [27]:
np.savez('testxy',x,y)

In [28]:
loadxy=np.load('testxy.npz',x,y)

In [29]:
loadxy

In [30]:
loadxy

In [32]:
loadxy["x"]

KeyError: 'x is not a file in the archive'

In [33]:
loadxy('y')

TypeError: 'NpzFile' object is not callable

In [34]:
loadxy['x']

KeyError: 'x is not a file in the archive'

In [35]:
x=np.random.randn(3,2)

In [36]:
y=np.random.randn(2,3)

In [37]:
x.dot(y)

array([[-0.34274323,  0.50443823,  0.24806728],
       [ 0.85607658, -1.29122881, -0.6236447 ],
       [ 2.13788076,  1.3750314 , -0.96311433]])

In [38]:
x.transpose()

array([[-0.57156857,  1.45005911,  0.3217319 ],
       [-0.05718643,  0.15672315, -1.65049641]])

In [39]:
x.trace()

-0.41484541813212394