In [2]:
import numpy as np

In [3]:
x = np.array([10,9,8,6,11])

In [4]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [6]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [7]:
y =[7,1,2,3,-1]

In [9]:
np.maximum(x,y)

array([10,  9,  8,  6, 11])

In [11]:
salary = np.array([0,-1,100000,50000])

In [12]:
np.where(salary<=0,25000,salary)

array([ 25000,  25000, 100000,  50000])

In [13]:
np.where(salary<=0,"Not Ok","Ok")

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

In [14]:
x=np.array([10,9,7,10,7])

In [15]:
x.mean()

8.6

In [18]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [19]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [20]:
y=x>6

In [21]:
y

array([ True,  True,  True,  True,  True])

In [22]:
y.sum()

5

In [24]:
y.any()

True

In [25]:
y.all()

True

In [26]:
y = x>7

In [27]:
y.sum()

3

In [28]:
y.any()

True

In [29]:
y.all()

False

In [30]:
x.sort()

In [31]:
x

array([ 7,  7,  9, 10, 10])

In [32]:
np.unique(x)

array([ 7,  9, 10])