In [1]:
l = range(1000000)

In [2]:
import numpy as np

In [4]:
d = np.arange(1000000)

In [5]:
%time for i in range(1,10): [x*2 for x in l]

Wall time: 1.44 s


In [6]:
%time for i in range(1,10): r=d*2

Wall time: 32 ms


In [7]:
x = np.zeros((4,4))

In [8]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((7,7))

array([[1.15565179e-311, 1.15564475e-311, 1.68821038e+195,
        1.49003499e+195, 5.70932366e+228, 4.76659976e+180,
        4.65688237e+164],
       [8.78422036e+247, 2.19529495e-152, 7.49363265e+247,
        2.39294633e-258, 6.07886271e+247, 3.93501887e+024,
        2.52301636e-258],
       [4.47593816e-091, 5.28595595e-085, 5.98115753e-114,
        1.28822630e-057, 8.44250580e-053, 9.08967386e+242,
        1.05135744e-153],
       [2.65862877e-260, 8.39459671e+217, 4.41496367e+222,
        3.02012407e-110, 1.05191453e-153, 9.66890684e+242,
        9.78375159e+199],
       [4.83245960e+276, 9.91598802e-096, 1.15296929e-259,
        8.94213159e+130, 4.56340382e-072, 7.57854830e-010,
        6.98028752e+199],
       [3.92675050e+223, 6.98387920e-077, 5.04050503e+223,
        3.74165235e+233, 3.74165281e+233, 2.87350346e+159,
        2.13389712e+161],
       [1.06024692e-153, 6.99416121e-009, 7.35280766e+223,
        3.74795232e+233, 2.84845496e-110, 5.70618215e+257,
        1.42395775

In [11]:
l=[1,4,5,7]

In [12]:
np.array(l)

array([1, 4, 5, 7])

In [15]:
x = np.arange(1,300,50)

In [16]:
x.shape

(6,)

In [17]:
x = np.zeros((10,10))

In [18]:
x.shape

(10, 10)

In [19]:
y = x.reshape(2,2,5,5)

In [20]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [21]:
y.dtype

dtype('float64')

In [22]:
y.ndim

4

In [24]:
a =np.random.randn((10))

In [25]:
b= np.random.randn((10))

In [26]:
a+b

array([ 1.74464844,  0.1248125 , -1.38763747, -1.87419551,  0.56384912,
       -0.18246354,  0.21770248, -0.0409943 , -1.57265695, -0.3292779 ])

In [27]:
a-b

array([ 0.20369966,  0.46559178,  0.26688116, -0.64563279,  1.34984913,
       -1.49498689, -0.33938266, -2.02767446,  1.50183064,  0.9857486 ])

In [28]:
2*a

array([ 1.94834811,  0.59040428, -1.12075631, -2.5198283 ,  1.91369825,
       -1.67745043, -0.12168018, -2.06866877, -0.0708263 ,  0.6564707 ])

In [30]:
1/a

array([  1.02651061,   3.38750931,  -1.78450925,  -0.79370487,
         1.04509684,  -1.19228561, -16.43653072,  -0.96680534,
       -28.23809733,   3.04659447])

In [31]:
a>0

array([ True,  True, False, False,  True, False, False, False, False,
        True])

In [32]:
a[a>0]

array([0.97417405, 0.29520214, 0.95684912, 0.32823535])

In [35]:
x =np.array([1,7,9,8,5])

In [37]:
x[4]

5

In [38]:
x[x>5]

array([7, 9, 8])

In [39]:
x[[2,1]]

array([9, 7])

In [41]:
a =np.random.randn(10,10)

In [42]:
a

array([[-0.03264675,  0.1867417 ,  0.68030298,  0.13522251, -3.02866499,
        -2.16868945, -0.95295012,  0.81208559, -0.60785252,  1.06266468],
       [-0.86805378, -0.44803455, -0.77026585, -0.98315025,  2.07135261,
        -0.74679237,  1.27608008, -0.52054273, -0.35406361, -0.64255893],
       [-2.4952682 , -0.46466087, -0.69422692,  1.45292245, -0.84170702,
         0.5212673 ,  1.94337083, -0.68777165, -0.87914632,  0.53970485],
       [-0.08408834,  0.77273882, -0.2874737 ,  0.57252371, -1.13941074,
        -0.3829486 , -0.93365513, -0.12220789, -1.57037377, -1.11744754],
       [-0.26305222,  0.63871901, -1.74247519, -1.27009756,  0.36505608,
        -0.91204287,  0.85377472, -1.07938644, -0.39476631, -0.4899723 ],
       [ 1.21200453,  1.11474183, -0.42331261,  0.46482166, -0.6381695 ,
        -0.5721926 ,  0.41646344,  0.47462581, -0.04379079, -0.55749419],
       [-0.85852825, -1.50084378, -0.60520837,  0.88516986,  0.32391725,
        -0.79553642,  1.00273953, -0.07408048

In [43]:
a[0]

array([-0.03264675,  0.1867417 ,  0.68030298,  0.13522251, -3.02866499,
       -2.16868945, -0.95295012,  0.81208559, -0.60785252,  1.06266468])

In [44]:
a[0][4]

-3.028664993844604

In [45]:
a[1:10:2]

array([[-0.86805378, -0.44803455, -0.77026585, -0.98315025,  2.07135261,
        -0.74679237,  1.27608008, -0.52054273, -0.35406361, -0.64255893],
       [-0.08408834,  0.77273882, -0.2874737 ,  0.57252371, -1.13941074,
        -0.3829486 , -0.93365513, -0.12220789, -1.57037377, -1.11744754],
       [ 1.21200453,  1.11474183, -0.42331261,  0.46482166, -0.6381695 ,
        -0.5721926 ,  0.41646344,  0.47462581, -0.04379079, -0.55749419],
       [-0.80353758,  0.24558893,  0.96755293,  0.30540218,  0.86122268,
         0.05955965, -0.82182962,  0.17076403,  1.21142132,  0.3532906 ],
       [-0.97587693,  0.80111012,  0.40098432,  0.25594692, -0.26188077,
        -1.08838218,  1.11336332,  0.22491522, -1.53250069, -0.96391371]])

In [47]:
a[::,0:4]

array([[-0.03264675,  0.1867417 ,  0.68030298,  0.13522251],
       [-0.86805378, -0.44803455, -0.77026585, -0.98315025],
       [-2.4952682 , -0.46466087, -0.69422692,  1.45292245],
       [-0.08408834,  0.77273882, -0.2874737 ,  0.57252371],
       [-0.26305222,  0.63871901, -1.74247519, -1.27009756],
       [ 1.21200453,  1.11474183, -0.42331261,  0.46482166],
       [-0.85852825, -1.50084378, -0.60520837,  0.88516986],
       [-0.80353758,  0.24558893,  0.96755293,  0.30540218],
       [ 0.42956577,  1.22905281,  0.4726226 , -0.18005613],
       [-0.97587693,  0.80111012,  0.40098432,  0.25594692]])

In [48]:
z =np.ones((5,5))

In [49]:
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
z[1:-1,1:-1]=0


In [51]:
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])