In [1]:
import pandas as pd

In [2]:
obj=pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [3]:
sales = pd.Series([100,200,100,400])
print(sales.values)
print(sales.index)
print(sales)

[100 200 100 400]
RangeIndex(start=0, stop=4, step=1)
0    100
1    200
2    100
3    400
dtype: int64


In [4]:
sales = pd.Series([100,200,100,400],index=['a','b','c','d'])
print(sales)

a    100
b    200
c    100
d    400
dtype: int64


In [5]:
sales = pd.Series([100,200,100,400],index=['Jan','Feb','March','April'])
print(sales)
print(sales.values)
print(sales.index)

Jan      100
Feb      200
March    100
April    400
dtype: int64
[100 200 100 400]
Index(['Jan', 'Feb', 'March', 'April'], dtype='object')


In [6]:
sales = pd.Series([100,200,100,400],index=['Jan','Feb','March','April'],name="4 month sales")
print(sales)

Jan      100
Feb      200
March    100
April    400
Name: 4 month sales, dtype: int64


# Create a pandas series to store a canteen data to hold values of how many sandwithes are sold each days(one week)

In [7]:
sw = pd.Series([20,30,20,25,30,40,0],index=['mon','tue','wed','thr','fri','sat','sun'])
print(sw)

mon    20
tue    30
wed    20
thr    25
fri    30
sat    40
sun     0
dtype: int64


In [8]:
print(sw[1])
print(sw['tue'])
print(sw['sun'])
print(sw[6])

30
30
0
0


# How we acces multiple values

In [9]:
print(sw[[3,5]])
print(sw[ ['tue','thr']])

thr    25
sat    40
dtype: int64
tue    30
thr    25
dtype: int64


# for providing multiple index for selecting element in an pd series,use array notation

In [10]:
# conditional 
print(sw[sw >20])

tue    30
thr    25
fri    30
sat    40
dtype: int64


In [11]:
sw*2
sw=sw*2
print(sw)

mon    40
tue    60
wed    40
thr    50
fri    60
sat    80
sun     0
dtype: int64


In [12]:
print(sw)

mon    40
tue    60
wed    40
thr    50
fri    60
sat    80
sun     0
dtype: int64


In [13]:
sw = sw/2
print(sw)

mon    20.0
tue    30.0
wed    20.0
thr    25.0
fri    30.0
sat    40.0
sun     0.0
dtype: float64


In [14]:
# how we check or search index present in series 
'mon' in sw

True

In [15]:
import numpy as np 
ar = np.array([3,2,4,5,6])
ind = np.array(['a','b','c','d','e'])

obj2=pd.Series(ar,index=ind)
print(obj2)

a    3
b    2
c    4
d    5
e    6
dtype: int32


In [16]:
# how we collect data from dictionary
sdata={'Sindh':35000,'punjab':4500,'Kpk':3000,"Balochistan":2000}
tax_by_state=pd.Series(sdata)
print(tax_by_state)
print(tax_by_state.index)
print(tax_by_state.values)

Sindh          35000
punjab          4500
Kpk             3000
Balochistan     2000
dtype: int64
Index(['Sindh', 'punjab', 'Kpk', 'Balochistan'], dtype='object')
[35000  4500  3000  2000]


In [17]:
# how we change value arrangement by the help of index indicator(as i provide key)
sdata={'Sindh':35000,'Punjab':5500,'Kpk':30000,"Balochistan":2000}
tax_by_state=pd.Series(sdata,index=['Punjab','Sindh','Kpk','Balochistan'])
print(tax_by_state)

Punjab          5500
Sindh          35000
Kpk            30000
Balochistan     2000
dtype: int64


#  **Source for Series Data**
* direct data in the series  method
* from Numpy array or list
* from python Dictionary

In [18]:
sdata={'Sindh':35000,'Punjab':5500,'Kpk':30000,"Balochistan":2000}
tax_by_state=pd.Series(sdata,index=['Punjab','Sindh','Kpk','Balochistan','Gb'])
print(tax_by_state)
print(pd.isnull(tax_by_state))

Punjab          5500.0
Sindh          35000.0
Kpk            30000.0
Balochistan     2000.0
Gb                 NaN
dtype: float64
Punjab         False
Sindh          False
Kpk            False
Balochistan    False
Gb              True
dtype: bool


In [19]:
tax_by_state.name="state tax paying capicity"
tax_by_state.index.name="stats name"
print(tax_by_state)
print(tax_by_state.index)

stats name
Punjab          5500.0
Sindh          35000.0
Kpk            30000.0
Balochistan     2000.0
Gb                 NaN
Name: state tax paying capicity, dtype: float64
Index(['Punjab', 'Sindh', 'Kpk', 'Balochistan', 'Gb'], dtype='object', name='stats name')


In [20]:
# NaN values mean,values does not exist in pandas series
pd.isnull(tax_by_state)
tax_by_state.isnull()

stats name
Punjab         False
Sindh          False
Kpk            False
Balochistan    False
Gb              True
Name: state tax paying capicity, dtype: bool

In [21]:
sw=pd.Series([20,30,20,25,30,40,0],index = ['mon','tue','wed','thr','fri','sat','sun'])

print(sw)
sw.index=['m','t','w','t','f','s','s']
print(sw)

mon    20
tue    30
wed    20
thr    25
fri    30
sat    40
sun     0
dtype: int64
m    20
t    30
w    20
t    25
f    30
s    40
s     0
dtype: int64


In [33]:
apples= pd.Series([1,2,3,4,5,6])
oranges=pd.Series([6,7,8,9,10,11])
print(apples,oranges)
df = {"Apples":apples,"Oranges":oranges}
fruits_df=pd.DataFrame(df)
fruits_df

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64 0     6
1     7
2     8
3     9
4    10
5    11
dtype: int64


Apples  Oranges
0       1        6
1       2        7
2       3        8
3       4        9
4       5       10
5       6       11

In [43]:
state=['Ohio','Ohio','Ohio','Nevenda','Nevenda','Nevenda']
year=[2001,2002,2003,2001,2002,2003]
pop=[1.2,1.3,1.4,1.2,1.3,1.4]
frame={'States':state,'Years':year,'Pop':pop}
frame_1=pd.DataFrame(frame,index=['1st','2nd','3rd','4th','5th','6th'])
print(frame_1)


      States  Years  Pop
1st     Ohio   2001  1.2
2nd     Ohio   2002  1.3
3rd     Ohio   2003  1.4
4th  Nevenda   2001  1.2
5th  Nevenda   2002  1.3
6th  Nevenda   2003  1.4


In [44]:
frame_1.head()

States  Years  Pop
1st     Ohio   2001  1.2
2nd     Ohio   2002  1.3
3rd     Ohio   2003  1.4
4th  Nevenda   2001  1.2
5th  Nevenda   2002  1.3

In [46]:
frame_1=pd.DataFrame(frame,columns=["Years","States","Pop"])
frame_1.head()

Years   States  Pop
0   2001     Ohio  1.2
1   2002     Ohio  1.3
2   2003     Ohio  1.4
3   2001  Nevenda  1.2
4   2002  Nevenda  1.3

In [50]:
frame_1=pd.DataFrame(frame,columns=["Years","States","op"])
frame_1.head()

Years   States   op
0   2001     Ohio  NaN
1   2002     Ohio  NaN
2   2003     Ohio  NaN
3   2001  Nevenda  NaN
4   2002  Nevenda  NaN

In [51]:
frame_1=pd.DataFrame(frame,columns=["Years","States","Pop","Debt"],index=['one','two','three','four','five','six'])
frame_1.head()

Years   States  Pop Debt
one     2001     Ohio  1.2  NaN
two     2002     Ohio  1.3  NaN
three   2003     Ohio  1.4  NaN
four    2001  Nevenda  1.2  NaN
five    2002  Nevenda  1.3  NaN

In [53]:
frame_1.columns

Index(['Years', 'States', 'Pop', 'Debt'], dtype='object')

In [54]:
frame_1.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [56]:
frame_1["States"]

one         Ohio
two         Ohio
three       Ohio
four     Nevenda
five     Nevenda
six      Nevenda
Name: States, dtype: object

In [57]:
frame_1.Years

one      2001
two      2002
three    2003
four     2001
five     2002
six      2003
Name: Years, dtype: int64

In [59]:
frame_1.loc["two"]

Years     2002
States    Ohio
Pop        1.3
Debt       NaN
Name: two, dtype: object