In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,-7,8,9,3,6])
print(obj)

0    4
1   -7
2    8
3    9
4    3
5    6
dtype: int64


In [3]:
Sales = pd.Series([100,200,600,500])
print(Sales.values)
print(Sales.index)
print(Sales)

[100 200 600 500]
RangeIndex(start=0, stop=4, step=1)
0    100
1    200
2    600
3    500
dtype: int64


In [4]:
Sales = pd.Series([100,200,600,500],index=['a','b','c','d'])
print(Sales.values)
print(Sales.index)
print(Sales)

[100 200 600 500]
Index(['a', 'b', 'c', 'd'], dtype='object')
a    100
b    200
c    600
d    500
dtype: int64


In [5]:
Sales = pd.Series([100,200,600,500],index=['Jan','Feb','Mar','Apr'])
print(Sales.values)
print(Sales.index)
print(Sales)

[100 200 600 500]
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')
Jan    100
Feb    200
Mar    600
Apr    500
dtype: int64


In [6]:
Sales = pd.Series([100,200,600,500],index=['Jan','Feb','Mar','Apr'],name="04 Months Sales")
print(Sales.values)
print(Sales.index)
print(Sales)

[100 200 600 500]
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')
Jan    100
Feb    200
Mar    600
Apr    500
Name: 04 Months Sales, dtype: int64


In [9]:
SW=pd.Series([50,40,45,60,70,55,65],index=['Mon','Tue','Wed','Thr','Fri','Sat','Sun'],name='01 Week Sales')
print(SW)

Mon    50
Tue    40
Wed    45
Thr    60
Fri    70
Sat    55
Sun    65
Name: 01 Week Sales, dtype: int64


In [12]:
print(SW[1])
print(SW['Fri'])
print(SW['Sun'])

40
70
65


In [13]:
print(SW[6])

65


In [16]:
print(SW[4:7])

Fri    70
Sat    55
Sun    65
Name: 01 Week Sales, dtype: int64


In [22]:
print(SW[[2,5]])
print(SW[['Fri','Sun']])

Wed    45
Sat    55
Name: 01 Week Sales, dtype: int64
Fri    70
Sun    65
Name: 01 Week Sales, dtype: int64


In [25]:
print(SW[SW>50])

Thr    60
Fri    70
Sat    55
Sun    65
Name: 01 Week Sales, dtype: int64


In [26]:
print(SW[SW<60])

Mon    50
Tue    40
Wed    45
Sat    55
Name: 01 Week Sales, dtype: int64


In [27]:
SW*2

Mon    100
Tue     80
Wed     90
Thr    120
Fri    140
Sat    110
Sun    130
Name: 01 Week Sales, dtype: int64

In [29]:
SW//2

Mon    25
Tue    20
Wed    22
Thr    30
Fri    35
Sat    27
Sun    32
Name: 01 Week Sales, dtype: int64

In [30]:
SW-2

Mon    48
Tue    38
Wed    43
Thr    58
Fri    68
Sat    53
Sun    63
Name: 01 Week Sales, dtype: int64

In [31]:
SW+8

Mon    58
Tue    48
Wed    53
Thr    68
Fri    78
Sat    63
Sun    73
Name: 01 Week Sales, dtype: int64

In [32]:
'Mon' in SW

True

In [33]:
import numpy as np
arr = np.arange(6)
ind = np.array(['a','b','c','d','e','f'])
data= pd.Series(arr,index=ind)
print(data)

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32


In [37]:
census_data = {"shakrail":2000,"Khanapull":3000,'Ghouritown':5000}
cd = pd.Series(census_data)
print(cd)
print(cd.index)
print(cd.values)

shakrail      2000
Khanapull     3000
Ghouritown    5000
dtype: int64
Index(['shakrail', 'Khanapull', 'Ghouritown'], dtype='object')
[2000 3000 5000]


In [43]:
census_data = {"shakrail":2000,"Khanapull":3000,'Ghouritown':5000}
ind = pd.Series(census_data,index=['Ghouritown','shakrail','Khanapull','Karal'])
print(ind)
print(ind.index)
print(ind.values)
print(pd.isnull(ind))

Ghouritown    5000.0
shakrail      2000.0
Khanapull     3000.0
Karal            NaN
dtype: float64
Index(['Ghouritown', 'shakrail', 'Khanapull', 'Karal'], dtype='object')
[5000. 2000. 3000.   nan]
Ghouritown    False
shakrail      False
Khanapull     False
Karal          True
dtype: bool


In [49]:
ind.name="Census 2016"
ind.index.name="Area"
print(ind)
print(ind.values)
print(ind.index)

Area
Ghouritown    5000.0
shakrail      2000.0
Khanapull     3000.0
Karal            NaN
Name: Census 2016, dtype: float64
[5000. 2000. 3000.   nan]
Index(['Ghouritown', 'shakrail', 'Khanapull', 'Karal'], dtype='object', name='Area')


In [50]:
pd.isnull(ind)

Area
Ghouritown    False
shakrail      False
Khanapull     False
Karal          True
Name: Census 2016, dtype: bool

In [51]:
ind.isnull()

Area
Ghouritown    False
shakrail      False
Khanapull     False
Karal          True
Name: Census 2016, dtype: bool